
version: '3.7'

services:
  web:
    image: ruhshan/date-server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/opt/code
    ports:
      - "8000"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "5000:5000"